### ISSUE TITLE
Server crashing and corrupting

### ISSUE THREAD

**Issue by AzusaNakanoSwe** [BevoTechPack/BevoTechPack#880] opened 2015-12-16 14:02 UTC
[crash-2015-12-16_14.49.29-server.txt](https://github.com/BevoTechPack/BevoTechPack/files/64058/crash-2015-12-16_14.49.29-server.txt)

It's in swedish though

![10359349_1043815005639882_5590535_o](https://cloud.githubusercontent.com/assets/16322321/11842768/009caaae-a406-11e5-94b4-9b607ab29aee.jpg)

Can someone plz help me with this :C

**Comment by b0bst3r** [comment] 2015-12-16 21:01
This is usually caused by an Antivirus or anti malware locking the file (multipart.dat) try disabling your AV and try it.

**Comment by b0bst3r** [comment] 2016-02-08 19:31
No reply within 24 days closing issue

**Closed by b0bst3r** 2016-02-08 19:31 UTC
