### ISSUE TITLE
Minecraft crashed alltime

### ISSUE THREAD

**Issue by xILikepuddingx** [BevoTechPack/BevoTechPack#1035] opened 2016-07-26 11:52 UTC
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version : Reborn Release 1.0
### Description of issue/bug

Problem 1: Minecraft closed instant and go back to the AT Launcher
Problem 2: Close Minecraft after a few minutes and back to the AT Launcher
### Steps to reproduce the issue/bug

Delete Instance, delete Optifine, reinstall AT Launcher
rename the file logintimes.dat to logintimes.old
delete chickenchunks.cfg and run the pack
i followed the steps:

> Back up any worlds you would like saved
>     Delete the instance of BTP
>     Restart computer. (Yes, actually restart your computer)
>     Re-install the pack. Restart computer again (Yes, again.)
>         Install any of the optional mods from the ATL menu ONLY
>         Do not add any other mods for this troubleshoot experience
> 
> Done? Great! Now... For the weird instructions.
> 
> ```
> After your computer is restarted
> Open ATL and launch pack
> ```
> 
> Did it launch all the way?
> 
> ```
> Yes: Profit!
>     Let me us know it worked please
>     I accept praise as payment
> No
>     Post the crash log to Pastbin or Gist and Link Here
>     Post the fml-client-latest.log
> ```
> 
> If you do crash, please also provide the following information:
> 
> ```
> Operating System
> Any security software running on the computer such as:
>     Anti-Virus
>     Malware scanners
> ```

and this

> @xILikepuddingx move your minecraft directory off of the desktop and onto your C:\ drive.
> 
> ```
> Take the ATL folder here: C:\Users\Animex3\Desktop\ATL\
> And make it look like: C:\ATL\
> Try again. New logs also if it crashes please.
> ```

updated the pack to release 1.0

http://pastebin.com/raw/0NuT8THs
http://pastebin.com/0FgB4L1b
http://pastebin.com/knQZRc59
http://pastebin.com/PPfZi8VH
http://pastebin.com/cBCNRwZc
[fml-client-latest.zip](https://github.com/BevoTechPack/BevoTechPack/files/440234/fml-client-latest.zip)
http://pastebin.com/19Y7am6y
http://pastebin.com/8sX6HSN7

Questions:

Did you add any additional mods? -  yes optifine, lucky blocks, portal gun
Do you use optifine? - yes
Did the problem appear in single player or on a server? -  Single Player

edit: 23.08.2016 - 16:54
edit2: 24.08.2016 - 18:30
edit3: 26.08.2016 - 23:49
edit4: 02.09.2016 - 08:57

**Comment by b0bst3r** [comment] 2016-07-26 13:49
Does this file exist?

C:\Users\Animex3\Desktop\ATL\Instances\BevosTechPack\saves\New World\chickenchunks\loginTimes.dat

**Comment by xILikepuddingx** [comment] 2016-07-26 14:06
yes

**Comment by b0bst3r** [comment] 2016-07-26 15:18
Try renaming it to like loginTimes.old and see if that helps, if not you might have to remove the chickenchunks mod, load up your world, save it, put the mod back in and try again.

**Comment by xILikepuddingx** [comment] 2016-08-21 15:04
Dont work
Without ChickenChunk works fine but with this mod crash

http://pastebin.com/0FgB4L1b

**Comment by b0bst3r** [comment] 2016-08-21 16:38
Does this exist - C:\Users\Animex3\Desktop\ATL\Instances\BevosTechPack\config\ChickenChunks.cfg

**Comment by xILikepuddingx** [comment] 2016-08-21 17:06
Yes

**Comment by b0bst3r** [comment] 2016-08-22 00:17
Delete it and run the pack it will generate a new one.

**Comment by xILikepuddingx** [comment] 2016-08-22 08:27
Dont work

http://pastebin.com/knQZRc59

**Comment by xILikepuddingx** [comment] 2016-08-22 16:19
And i ive a other problem

i cant craft the carry (machine base cant find) by BC Builders.

**Comment by b0bst3r** [comment] 2016-08-22 17:04
That machine base is actually the BC quarry, which is disabled by me in the pack, there are several better alternatives to quarrying than digging big holes in your worlds.

**Comment by xILikepuddingx** [comment] 2016-08-22 17:57
Ok but ive still the problem with the chickenchunk mod

**Comment by b0bst3r** [comment] 2016-08-22 18:48
Apart from reinstalling the instance I'm stuck for helping any further

**Comment by xILikepuddingx** [comment] 2016-08-22 19:33
reinstall dont work

http://pastebin.com/PPfZi8VH

**Comment by xILikepuddingx** [comment] 2016-08-22 20:02
ive maybe a idea

i opened the ChickenChunks.cfg:

```
#ChunkLoader Configuration File
#Deleting any element will restore it to it's default value
#Block ID's will be automatically generated the first time it's run

#Per player chunk limiting. Values ignored if 0.:Simply add <username>=<value>
players
{
	#Forge gives everyone 12500 by default
	DEFAULT=5000
	#For server op's only.
	OP=5000
}

#If set to false, players will have to be logged in for their chunkloaders to work.:Simply add <username>=<true|false>
allowoffline
{
	DEFAULT=true
	OP=true
}

#The number of minutes since last login within which chunks from a player will remain active, 0 for infinite.
awayTimeout=0

checkUpdates=true

#The number of ticks to wait between attempting to unload orphaned chunks
cleanuptime=1200

#The maximum number of chunks per chunkloader
maxchunks=400

#Enabling this lets OPs alter other player's chunkloaders. WARNING: If you change a chunkloader, you have no idea what may break/explode by not being chunkloaded.
op-interact=false

#Set to false to disable the automatic reloading of mystcraft dimensions on server restart
reload-dimensions=true

#Set to false to deny a player access to the chunk viewer
allowchunkviewer
{
	DEFAULT=true
	OP=true
}
```

i can play with the same version on ftb and i opened this:

> #ChunkLoader Configuration File
> #Deleting any element will restore it to it's default value
> #Block ID's will be automatically generated the first time it's run
> 
> #Per player chunk limiting. Values ignored if 0.:Simply add <username>=<value>
> players
> {
> 	#Forge gives everyone 12500 by default
> 	DEFAULT=5000
> 	#For server op's only.
> 	OP=5000
> }
> 
> #If set to false, players will have to be logged in for their chunkloaders to work.:Simply add <username>=<true|false>
> allowoffline
> {
> 	DEFAULT=true
> 	OP=true
> }
> 
> #Set to false to deny a player access to the chunk viewer
> allowchunkviewer
> {
> 	DEFAULT=true
> 	OP=true
> }
> 
> #The number of minutes since last login within which chunks from a player will remain active, 0 for infinite.
> awayTimeout=0
> 
> checkUpdates=true
> 
> #The number of ticks to wait between attempting to unload orphaned chunks
> cleanuptime=1200
> 
> #The maximum number of chunks per chunkloader
> maxchunks=400
> 
> #Enabling this lets OPs alter other player's chunkloaders. WARNING: If you change a chunkloader, you have no idea what may break/explode by not being chunkloaded.
> op-interact=false
> 
> #Set to false to disable the automatic reloading of mystcraft dimensions on server restart
> reload-dimensions=true
> 

I changed it but when I started brevo, moved it back to the old

**Comment by xILikepuddingx** [comment] 2016-08-26 04:20
need still help

**Comment by bookerthegeek** [comment] 2016-08-26 10:07
Please Follow these steps and report back with both the Crash report and the console Log:

- Back up any worlds you would like saved
- Delete the instance of BTP
- Restart computer. (Yes, actually restart your computer)
- Re-install the pack. Restart computer again (Yes, again.)
 - Install any of the optional mods from the ATL menu ONLY
 - Do not add any other mods for this troubleshoot experience

Done? Great! Now... For the weird instructions.
- After your computer is restarted
- Open ATL and launch pack

Did it launch all the way?
- Yes: Profit! 
 - Let me us know it worked please
 - I accept praise as payment
- No
 - Post the ````crash log```` to [Pastbin](http://pastebin.com/) or [Gist](https://gist.github.com/) and Link Here
 - Post the ````fml-client-latest.log````

If you do crash, please also provide the following information:
- Operating System
- Any security software running on the computer such as:
 - Anti-Virus
 - Malware scanners


Thank you and I look forward to your Profit!

**Comment by xILikepuddingx** [comment] 2016-08-26 20:41
Dont work but i found the problem

I just got the message that the codechickenlib could not be downloaded. I downloaded it manually , but he unfortunately did not work. The version: CodeChickenLib - 1.7.10-1.1.3.138. I looked for a newer version and then ive found the version: CodeChickenLib - 1.7.10-1.1.3.140. i inserted into the mods folder and launched BTP. now it seems to work.

**Comment by xILikepuddingx** [comment] 2016-08-26 21:48
But ive now my old problem:

http://pastebin.com/cBCNRwZc

i changed the name .bat to .old but it create a new .bat file

**Comment by xILikepuddingx** [comment] 2016-08-26 23:18
and ive this problem with the NEI

http://pastebin.com/F2EUQZRf

MC crashed when i pressed options

**Comment by bookerthegeek** [comment] 2016-08-27 05:35
@xILikepuddingx move your minecraft directory off of the desktop and onto your ````C:\```` drive.

- Take the ATL folder here: ````C:\Users\Animex3\Desktop\ATL\````
- And make it look like: ````C:\ATL\````
- Try again. New logs also if it crashes please.

**Comment by xILikepuddingx** [comment] 2016-08-27 07:11
Dont work

http://pastebin.com/19Y7am6y

**Comment by b0bst3r** [comment] 2016-08-29 15:29
Try updating to Release 1 and see if the problem is still present.

**Comment by xILikepuddingx** [comment] 2016-09-02 06:45
Update to release 1.0 but dont work

http://pastebin.com/8sX6HSN7

**Comment by bookerthegeek** [comment] 2016-09-02 20:44
Find this file:
````C:\ATL\Instances\BevosTechPack\config\ChickenChunks.cfg````
Open it up, and replace everything inside of it with[THIS](https://goo.gl/mWx2yS)

**Comment by bookerthegeek** [comment] 2016-09-14 03:48
@xILikepuddingx Did you get it working?

**Comment by minecraft333** [comment] 2016-09-17 10:41
i have the same problem and it doesen´t work

**Comment by b0bst3r** [comment] 2016-09-17 11:16
Can you translate this  Der Vorgang ist bei einer Datei mit einem geöffneten Bereich, der einem Benutzer zugeordnet ist, nicht anwendbar

**Comment by minecraft333** [comment] 2016-09-17 17:23
The occurrence is with a file with an opened area which is assigned to a user, not applicable

**Comment by b0bst3r** [comment] 2016-09-18 01:55
Yeah that's what google said I was hoping for a proper translation.

**Comment by Watschman** [comment] 2016-09-19 13:52
"Der Vorgang ist bei einer Datei mit einem geöffneten Bereich, der einem Benutzer zugeordnet ist, nicht anwendbar." is a pretty complicated German sentence.
I as a German citizen would translate it like that: "The process from a file with an open field/area which is assigned to a user is not applicable."
The more important part of this crash though is the java.io.FileNotFoundException .
Apparently the game does not find / can not read the chickenchunks.cfg which is weird because it should create a new .cfg file if it can't read the file for some reason.

**Comment by xILikepuddingx** [comment] 2016-09-20 18:02
@bookerthegeek i tried this befor but it changed back to the old

**Comment by xILikepuddingx** [comment] 2016-09-20 19:00
@b0bst3r Sorry cant help, I would say the same as @Watschman. 

@Watschman ich denke du bist ein deutscher vermute ich?
Du meinst es kann Java nicht finden und dadurch kommt es zu dem Fehler, dass ATL nicht auf chickenchunks.cfg zugreifen kann?

ATL ist auf meiner C: Festplatte soweit ich weiß sowie Java.
Könnte es an der Java-Version liegen die ist momentan bei der aktuellen Version Java Version 8 Upgrade 101

**Comment by minecraft333** [comment] 2016-09-20 19:58
Also ich weiß die frage geht nicht an mich aber ich habe das gleiche Problem. Aber meine java Version ist die 8 (101) und es geht trotzdem nicht.

**Comment by ranger135xp** [comment] 2016-12-30 00:31
Try adding your ATL folder to the list of exceptions with your AV program as per this thread:
https://forum.feed-the-beast.com/threads/ftb-unleashed-randomly-crashes.33047/#post-455394

This would make sense as to why MC cannot access the file even when generating it. An outside force (like AV programs or NTFS permissions) could be stopping the access to the file.

**Closed** 2018-01-30 16:17 UTC
Labels: Awaiting Player Response
