### ISSUE TITLE
Mekanism Turbine Crash

### ISSUE THREAD

**Issue by nsawar18** [BevoTechPack/BevoTechPack#1020] opened 2016-07-09 13:56 UTC
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- V-NC to W-NC updating

**### Description of issue/bug**

Server crash when updating from V-NC to W-NC.  

**### Steps to reproduce the issue/bug**
Mekanism turbine with full steam.
Ender IO fluid pipe inputting steam into the turbine.

**### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)**
http://pastebin.com/piG2hhJX

**Fixed by:**
Taking out the turbine valve then replacing after the update.

Did you add any additional mods? - NO
Do you use optifine? - NO
Did the problem appear in single player or on a server? - Server

**Comment by b0bst3r** [comment] 2016-07-12 02:07
I've taken W off the recommended list, you'd think something so bad would warrant a quick hotfix release by mekanism :(

**Comment by lilmoefow** [comment] 2016-07-15 03:39
This crash also happens with Themal Dynamics Ducts 

http://pastebin.com/DvGz6cnS

**Comment by b0bst3r** [comment] 2016-07-15 10:57
Yeah the problem is not what's connected the issue is the valve block itself.

**Comment by b0bst3r** [comment] 2016-07-20 20:11
Well Mekanism fixed the issue but I have reservations about the new version because of 2 things.

1) Massive FPS drops and high CPU usage on the new Wind Turbine coding
2) Very irratic Osmium world gen 

Currently looking into the build more

**Comment by b0bst3r** [comment] 2016-07-29 02:37
Fixed in BetaX

**Closed by b0bst3r** 2016-07-29 02:37 UTC
