### ISSUE TITLE
Bevo Tech Pack Problem | Could not Installed

### ISSUE THREAD

**Issue by kiligo** [BevoTechPack/BevoTechPack#1027] opened 2016-07-23 09:43 UTC
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- Bevo's Tech Pack - BTP-Reborn-BetaV (Minecraft 1.7.10)

### Description of issue/bug
I cant install the pack. there is standing an error please help.
there is standing that something with a journeymap is not ok.

### Steps to reproduce the issue/bug
download and wait than came the issue.

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)

http://pastebin.com/Y0FA0UH0

Questions:

Did you add any additional mods? - no
Do you use optifine? - no
Did the problem appear in single player or on a server? -  The pack doesnt install

**Comment by b0bst3r** [comment] 2016-07-23 12:34
Duplicate of https://github.com/BevoTechPack/BevoTechPack/issues/1026

**Closed by b0bst3r** 2016-07-23 12:34 UTC
