### ISSUE TITLE
BTP 11 crashes with Fastcraft 1.12

### ISSUE THREAD

**Issue by OverlordDerp** [BevoTechPack/BevoTechPack#798] opened 2015-01-10 18:50 UTC
Crashes midway through loading, with this error report: pastebin.com/B80J7vNp

**Comment by sfPlayer1** [comment] 2015-01-11 02:59
I'd appreciate if you had reported this to the FastCraft thread as well..

It looks like this is caused by the coremod component of FastCraft not being loaded. Did you edit the jar?

**Comment by OverlordDerp** [comment] 2015-01-11 20:19
No jar editing was done. It was simply added to the mods folder to a vanilla install of Bevo Tech Pack. Also, totally slipped my mind to post this on the Fastcraft thread, my bad.

**Comment by sfPlayer1** [comment] 2015-01-11 22:10
FastCraft 1.13 will detect this fault if it's what I think it is. Grab it from the end of the FC thread and see what happens please.

**Comment by OverlordDerp** [comment] 2015-01-14 05:28
Works perfectly, thank you!

**Comment by Xfel** [comment] 2015-01-30 10:24
If it is working now, you should close this issue.

**Closed** 2015-01-31 04:20 UTC
